plugins:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  CacheRootDirectory: tmp/rubocop_cache
  Exclude:
    - bin/**/*
    - tmp/**/*
    - vendor/**/*
    - log/**/*
    - public/**/*
    - storage/**/*
    - web/**/*

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Rails/Delegate:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/EmptyStringInsideInterpolation:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Rails/Present:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

RSpec/ReceiveMessages:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false
